layout: page
title: "showcase"
permalink: /showcase/

theme: jekyll-theme-cayman
title: Zero5's Site
description: idk
show_downloads: true

github:
  showcase: http://zero5g.github.io/showcase/
  another_url: another value